#!/usr/bin/env bash

function val_track {
  search="$@"
  search="${search//'#'/'%23'}"
  search="${search//' '/'%20'}"
  open "https://tracker.gg/valorant/profile/riot/$search"
}

function val_cfg {
  bat '
  + Ability 1: TAB, RSHIFT
  + Ability 2: G
  + Ability 3: MOUSE5
  + Ultimate: H
  + Forward: W, MMB
  + Back: S
  + Right: D
  + Left: A
  + Walk: LCTRL, RCTRL
  + Jump: SPACE, LALT
  + Crouch: LSHIFT, LALT
  + Fire: MOUSE1
  + ADS: MOUSE2
  + Zoom: Q
  + Reload: R
  + Primary: WHEELUP
  + Secondary: WHEELDOWN
  + Melee: MOUSE4
  + Spike: 6
  + Drop: N
  + Inspect: F
  + Use: E
  + Plant/Defuse: 1
  + Spray: P
  + Party Voice: C
  + Team Voice: V
  + Ping: T
  + Combat Radio: [
  + Tactics Radio: ]
  + Combat Report: O
  + Ability Tooltip: I
  + Armory: B, MMB
  + Map Toggle:
  + Map Hold:  4
  + Scoreboard: GRAVE
  + Aim: 0.318
  + Scoped/ADS: 1
  + Map Size: 1.2
  + Map Zoom: 0.888
  + Stats: FPS, Frame Time, RTT, Packet Loss, Packets Lost
'
}

function val_cross {
  bat '
  # +

  `0;c;1;s;1;P;h;0;d;1;f;0;0l;4;0o;1;0a;1;0f;0;1b;0;S;c;0;t;000000FF;s;0.582;o;1`
  `0;p;0;c;1;s;1;P;h;0;f;0;m;1;0o;0;0a;1;0m;1;0f;0;0s;0.064;1b;0;A;h;0;0t;10;0l;2;0v;2;0a;1;0m;1;0f;0;0s;0.064;1b;0;S;c;0;t;000000FF;s;0.582;o;1`

  # •

  `0;p;0;c;1;s;1;P;c;5;u;FF69B4FF;h;0;f;0;m;1;0b;0;1t;4;1o;0;1a;1;1f;0;1s;0.05;A;c;5;h;0;0b;0;1t;8;1o;3;1a;1;1s;0.05;1e;0.05;S;c;0;s;0.371;o;1`
  `0;p;0;c;1;s;1;P;c;5;u;FF69B4FF;h;0;f;0;m;1;0b;0;1t;4;1l;1;1o;0;1a;1;1f;0;1s;0.05;A;c;5;h;0;0b;0;1t;8;1l;1;1o;3;1a;1;1s;0.05;1e;0.05;S;c;0;s;0.371;o;1`
  `0;p;0;c;1;s;1;P;c;5;u;FF69B4FF;h;0;f;0;m;1;0b;0;1t;4;1l;1;1v;1;1o;0;1a;1;1f;0;1s;0.05;A;c;5;h;0;0b;0;1t;8;1l;1;1v;1;1o;3;1a;1;1s;0.05;1e;0.05;S;c;0;s;0.371;o;1`
'
}

val_$@
