#!/usr/bin/env bash
set -e

sudo apt-get -y install bridge-utils
echo "
network:
    ethernets:
        eth0:
           dhcp4: false
           optional: true
        eth1:
           dhcp4: false
           optional: true
        wlan0:
           dhcp4: false
           optional: true
    bridges:
        br0:
            dhcp4: true
            interfaces:
                - eth0
                - eth1
                - wlan0
    version: 2
"
