#!/usr/bin/env bash
set -e

function _masqs_block {
  local hosts=( $@ 'https://winhelp2002.mvps.org/hosts.txt' )
  curl -s ${hosts[*]} \
    | grep '^0\.0\.0\.0' | grep -o '^[^#]*' \
    | sed -e 's/\r/\n/g' | sort | uniq | grep -v '^$'
}

function _masqs_denied { grep ': DHCPDISCOVER' /var/log/syslog | grep -iE 'no address'; }

function _masqs_edit {
  if [[ "$1" =~ ^g(uests)?$ ]]; then file='/etc/dnsmasq.d/masqs.guests'
  elif [[ "$1" =~ ^i(gnore)?$ ]]; then file='/etc/dnsmasq.d/masqs.ignore'
  elif [[ "$1" =~ ^h(hosts)?$ ]]; then file='/etc/hosts.masqs'; shift||:
    if [[ "$1" =~ ^g(uests)?$ ]]; then file+='.guests'
    elif [[ "$1" =~ ^b(locklist)?$ ]]; then file+='.blocklist'; fi
  else file='/etc/dnsmasq.d/masqs'; fi
  init_conf "$file"
  sudo vim $file
}

function _masqs_aps {
  [[ "$1" ]] && aps='mux' || exit
  while [[ "$1" ]]; do
    aps+=" 'forev clear sudo hostapd /etc/hostapd/${1}*'"; shift
  done
  bash -c "$aps"
}

function _masqs_fw {
  if [[ "$1" ]]; then wan="$1"; fi
  _masqs_guests | while read guest; do
    if [[ "$guest" != *'.local' ]]; then
      gawk -F, '{print "-A POSTROUTING -s "$2" -o "$4" -j MASQUERADE"}' <<< "$guest,${wan:-eth0}"
    fi
  done | sort -V
}

function _masqs_hosts {
  _masqs_guests | while read guest; do
    gawk -F, '{print tolower($2" "$3".box")}' <<< "$guest"
  done | sort -V
}

function _masqs_guests { cat /etc/dnsmasq.d/masqs.guests | grep '^dhcp-host='; }

function _masqs_rez { fw r; serv r dnsmasq; }

function _masqs_status { fw; serv s dnsmasq; }

function _masqs_leases { cat /var/lib/misc/dnsmasq.leases; }


function init_conf {
  if [[ -f "$1" ]]; then return; fi
  if [[ "$file" == '/etc/dnsmasq.d/masqs' ]]; then
    elevated "echo 'no-resolv
server=1.1.1.1
addn-hosts=/etc/masqs/hosts
addn-hosts=/etc/masqs/hosts.blocklist
addn-hosts=/etc/masqs/hosts.guests

interface={eth-static-guests}
dhcp-range=192.168.123.1,192.168.123.1,0m

interface={eth-dhcp-guests}
dhcp-range=192.168.234.2,192.168.234.255,72h' > /etc/dnsmasq.d/masqs

mkdir -p /etc/masqs; touch /etc/masqs/hosts /etc/masqs/hosts.blocklist /etc/masqs/hosts.guests"
  fi
}

function elevated { sudo su - root -c "$1"; }

# function _masqs_setup {
#   sudo vim /etc/sysctl.conf
#   sudo vim /etc/
# }

if [[ "$1" ]]; then _masqs_$@
else echo functions: `grep '^function _masqs_' $0 | $awk '{print $2}' | sed 's/_masqs_//g'`; fi
