#!/usr/bin/env bash
///usr/bin/env true; exec blobman rust "$0" $@

use std::env;
use std::io;

fn main() {
  for line in io::stdin().lines() { println!("{}", line.unwrap()); }
  let mut args: Vec<String> = env::args().collect();
  args.remove(0);
  for arg in args {
    println!("{}", arg);
  }
}
