#!/usr/bin/env bash
set -e

[[ ! "$stash" ]] && echo 'set stash' && exit ||:
cd "${stash_root:-.}"
mkdir -p ".stash/$stash"

if [[ "$1" == 'pop' ]]; then
  mv ".stash"/$stash .
  if [[ -d ".stash/$stash" ]]; then parrot yellow "$stash already popped"
  else mv "$stash" ".stash" || parrot red "$stash stash failed"; fi
else
  if [[ -d ".stash/$stash" ]]; then parrot yellow "$stash already stashed"
  else mv "$stash" ".stash" || parrot red "$stash stash failed"; fi
fi
