#!/usr/bin/env node

const shell = require('child_process').execSync; shell('npm i -g express body-parser')
const express = require('express')().use(require('body-parser').json())
const fs = require('fs')
const serverFile = process.argv[2] ?? 'server.json'
const server = fs.existsSync(serverFile) ? JSON.parse(fs.readFileSync(serverFile, 'utf8')) : {}
const root = server.root ?? '', port = server.port ?? 8080

function log(statusCode, req) {
  console.log(`${new Date().toLocaleTimeString()} ${statusCode} ${req.method} ${req.originalUrl}`)
}

for (const api of server.apis ?? [])
  express[(api.method ?? 'get').toLowerCase()](`${root}${api.route}` ?? '/', (req, res) => {
    let statusCode = api.status ?? 200
    log(statusCode, req);
    api.shell && shell(api.shell)
    api.eval && eval(api.eval)
    api.import && import(`${process.cwd()}/${api.import}`)
    res.status(statusCode)
      .send(api.response ?? {params: req.params ?? {}, query: req.query ?? {}, body: req.body ?? {}})
  })

express.all('*', function (req, res) {
  log(404, req)
  res.status(404).end()
});

express.listen(port, () => console.log(`listening on ${port}`))
