#!/usr/bin/env bash
///usr/bin/env true; exec blobman c++ "$0" $@

#include <iostream>

using namespace std;

int main(int argc, char **argv) {
  string line;
  while (cin >> line) {
    cout << line << endl;
  }
  for (int i = 1; i < argc; ++i) {
    cout << argv[i] << endl;
  }
  return 0;
}
